---
name: Dependencies ğŸ“„

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:

concurrency:
  group: dependencies-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: ${{ vars.CI_IMAGE }}
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.CI_IMAGE }}

    steps:
      - name: Checkout project â¬‡ï¸
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Install package dependencies ğŸ“„
        run: |
          args <- commandArgs(trailingOnly = TRUE)
          path <- args[1]
          if (file.exists(path)) {
              yaml::yaml.load(readLines(path))$dependencies |>
              sapply(function(x) x$repo) |>
              pak::pak(dependencies = TRUE, ask = FALSE, upgrade = FALSE)
            }
        shell: Rscript {0}
        working-directory: ${{ github.event.repository.name }}
        with:
          PATH: "dependencies.yml"
